<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchResultsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByTimesOccured($searchHistoyrId)
    {
        $entityManager = $this->getEntityManager();
    	$query = $entityManager->createQuery('SELECT p FROM AppBundle:SearchResults p WHERE p.searchHistoryId = :search_history_id ORDER BY p.timesRepeated DESC');
    	$query->setParameter('search_history_id', $searchHistoyrId);
		$data = $query->getResult();
        return $data;
    }

    public function findAllTopTenWords($searchHistoyrId)
    {
    	$entityManager = $this->getEntityManager();
    	$query = $entityManager->createQuery('SELECT p FROM AppBundle:SearchResults p WHERE p.searchHistoryId = :search_history_id ORDER BY p.timesRepeated DESC');
    	$query->setParameter('search_history_id', $searchHistoyrId);
		$query->setFirstResult(0);
		$query->setMaxResults(10);
		$data = $query->getResult();
        return $data;
    }
}
