<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchResultsRepository extends \Doctrine\ORM\EntityRepository
{
		/**
		 * Get results of search for a specific SearchHistory
		 * 
		 * @param  integer $searchHistoyrId
		 * 
		 * @return Object                  
		 */
	public function findOrderedByTimesOccuredBySeachHistoryId($searchHistoyrId)
    {
        $entityManager = $this->getEntityManager();
    	$query = $entityManager->createQuery('SELECT p FROM AppBundle:SearchResults p WHERE p.searchHistoryId = :search_history_id ORDER BY p.timesRepeated DESC');
    	$query->setParameter('search_history_id', $searchHistoyrId);
		$data = $query->getResult();
        return $data;
    }

    /**
     * Get top ten words of search results with searchHistoryId
     * 
     * @param  integer $searchHistoyrId 
     * 
     * @return Object                  
     */
    public function findAllTopTenWords($searchHistoyrId)
    {
    	$entityManager = $this->getEntityManager();
    	$query = $entityManager->createQuery('SELECT p FROM AppBundle:SearchResults p WHERE p.searchHistoryId = :search_history_id ORDER BY p.timesRepeated DESC');
    	$query->setParameter('search_history_id', $searchHistoyrId);
		$query->setFirstResult(0);
		$query->setMaxResults(10);
		$data = $query->getResult();
        return $data;
    }
}
